### ISSUE TITLE
Fix Whitespace Issues

### ISSUE THREAD

**Issue by Kilo59** [Kilo59/ruff-sync#6]
Updates to `pypoject.toml` introduces extra whitespace and/or remove too much whitespace.

```toml
[tool.ruff]
target-version = "py310"
line-length = 120
lint.select = ["F", "ASYNC", "RUFF", "B", "S", "PTH", "W", "E"]
lint.ignore = ["W191", "E111"]
# 1 too many newlines


[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401", # unused import
    "F403", # star imports
] # should be a newline after this table
[tool.coverage.run]
include = [
    "foo.py",
    "bar.py"
    ]

```
This is almost certainly introduced by trying to operate on individual `Table` items and then re-inserting them into the `TOMLDocument` rather than always just operating on the full document.
See `get_ruff_tool_table()` & `merge_ruff_toml()`.
